### ISSUE TITLE
Move save states to Onion Saves folder

### ISSUE THREAD

**Issue by schmurtzm** [steward-fu/nds#35]
The objective would be to move load_state and save_state to `/mnt/SDCARD/Saves/CurrentProfile/states/Drastic` .
As this modification concerns only Onion I suppose that a dedicated version of the drastic binary would be necessary with a detection of Onion in the launch script.

As reminder (credits Steward): 

> if we only need load_state anf save_state, it is also possible to do this by patching
![image](https://github.com/steward-fu/nds_miyoo/assets/7110113/42a11d94-a327-44e7-81d1-fba1b5b39f6d)

**Comment by steward-fu** [comment]
commit: https://github.com/steward-fu/nds_miyoo/commit/ba347780d23867de84be51011b855eb1a2d7e425

There is a new setting in resources/setting.json for states path, which names "states".

**Comment by neolao** [comment]
I suppose it's also possible to do the same thing with the backup files, right?

**Comment by schmurtzm** [comment]
@steward-fu 
It works very well for the save state triggered our keymon (save states go into `/mnt/SDCARD/Saves/CurrentProfile/states/Drastic`).
But if I press menu + R2 or by using the Drastic menu, the saves go into  `/mnt/SDCARD/Emu/NDS/savestates`.
Is it possible to systematically redirect all the save states into `/mnt/SDCARD/Saves/CurrentProfile/states/Drastic` (which means that the Drastic menu will load it from here too).



> I suppose it's also possible to do the same thing with the backup files, right?

Yes it would be an improvement even if most users will use save states. But I don't want to ask too much to Steward and this kind of redirection is tricky.

**Comment by neolao** [comment]
> Yes it would be an improvement even if most users will use save states.

oh really? I consider the states as a "(very) nice to have" feature. Several times I've overwritten a state. But the real save is the one I make in the game. 🤷‍♂️

**Comment by schmurtzm** [comment]
Yes really 🤔 I already know that if you ask for it it means that you use it, but it doesn't mean that your use reflecting the habits of most of our users ;) 

But anyway, I agree on the fact that it would be more clean to have all what is related to saves to the Saves folder : 
- savestates from `/mnt/SDCARD/Emu/NDS/savestates` to `/mnt/SDCARD/Saves/CurrentProfile/states/Drastic`
- saves from `/mnt/SDCARD/Emu/NDS/backup` to `/mnt/SDCARD/Saves/CurrentProfile/saves/Drastic`

From what I know it's not necessarily feasible...

**Comment by steward-fu** [comment]
Yes, all of save files (in both backup and savestates) should be put in the same parent folder, ex: /mnt/SDCARD/Saves/CurrentProfile/saves/Drastic folder.
I will try to implement it, thanks :)

**Comment by steward-fu** [comment]
commit: https://github.com/steward-fu/nds/commit/fe775926de2cb290f69c6900e1c828acb034270f

**Comment by steward-fu** [comment]
I put all of save files together for management more easily. If this is not you want, please drop a comment to let me know.

**Comment by neolao** [comment]
Ok for me, I prefer every save files in the same folder.
