### ISSUE TITLE
No sound in MinUI

### ISSUE THREAD

**Issue by jmapagchema** [steward-fu/nds#36]
I Know that it's not a issue at all, but i wish you can make magic!

Drastic runs very fine in miyoo mini and plus on MinUI, the only thing that doesn't work is sound. I have tried any available 'fix' but i can't make it sound.

Maybe you can make alternative launch.sh or config to make it works with sound on MinUI?

The RG35XX Version of Drastic runs perfect in MinUI...

**Comment by steward-fu** [comment]
Could you provide the MinUI's installation file or the GitHub link ?

**Comment by jmapagchema** [comment]
Sure, there it is MinUI: https://github.com/shauninman/[MinUI](https://github.com/shauninman/MinUI)

And there is the RG35XX version ported to MinUI: https://boosty.to/xquader/posts/b9bfd9b4-5a37-48a6-8bc7-3d8aa48a5953?share=post_link

Thanks!!!!

**Comment by pakrett** [comment]
Allium by [Goh Wei Wen](https://github.com/goweiwen) has this kind of issue too, someone has managed to fix it but unfortunatly it doesn't work on MinUI.

I put the link here here maybe it can help.

https://github.com/goweiwen/Allium/issues/48

**Comment by jmapagchema** [comment]
I've tried these fix and others with no luck :(

**Comment by jmapagchema** [comment]
Ohhh this is the question. The audio fix... the only difference from RG35XX where Drastic works perfectly in MinUI.

**Comment by pakrett** [comment]
> Error log:
> 
> ```
> [MI ERR ]: MI_AO_SetPubAttr[3364]: Dev0 failed to set pub attr!!! error number:0xa0052009!!!
> [SND] failed to set PubAttr
> ```
> 
> DraStic emulator relies on "Audio Fix" setting. This is why it fails when start game. Please file issue back to MinUI GitHub to support "Audio Fix" setting. For "Audio Fix" setting, maybe, you can refer to the implementation of Onion or Stock system.

There is no issues tab on MinUI github unfortunatly, maybe you can redirect me to the part of the code in onion os? I don't know if [Shaun Inman](https://github.com/shauninman) takes feature request without proper code.

**Comment by jmapagchema** [comment]
OnionOS doesn't have drastic on their code... I think Onion uses this steward-fu build in their system. Shauninman doesn't have issues available, I've contacted him trough X, and with this link. I hope he can see it.

**Comment by pakrett** [comment]
> OnionOS doesn't have drastic on their code... I think Onion uses this steward-fu build in their system. Shauninman doesn't have issues available, I've contacted him trough X, and with this link. I hope he can see it.

I'm talking about the audio fix part of the code, not drastic.

**Comment by steward-fu** [comment]
Honestly, I am not familiar with "Audio Fix". As I remembered, when I first time ported drastic emulator to miyoo mini plus, I noticed that the audio doesn't work. After told by someone, I turned off "Audio Fix" and then the sound works as expected. So, when drastic emulator starts to run, the first thing is to kill audio related service (in launch.sh file). I also checked on MinUI system, no any related service is alive. So, I really don't know why the sound doesn't work.

**Comment by bqcuong** [comment]
@jmapagchema If you are still following this, here is my temporary workaround (MinUI + Miyoo Mini Plus):

1. Add the following code right before the call to [`./drastic`](https://github.com/steward-fu/nds/blob/master/assets/mmiyoo/launch.sh#L62) in `NDS.pak/launch.sh` (follow this [suggestion](https://github.com/goweiwen/Allium/issues/48#issuecomment-1809203134)).
```bash
set_snd_level() {
    local start_time
    local elapsed_time

    start_time=$(date +%s)
    while [ ! -e /proc/mi_modules/mi_ao/mi_ao0 ]; do
        sleep 0.2
        elapsed_time=$(( $(date +%s) - start_time ))
        if [ "$elapsed_time" -ge 3 ]; then
            return 1
        fi
    done

    echo "set_ao_mute 0" > /proc/mi_modules/mi_ao/mi_ao0
    echo "set_ao_volume 0 -30dB" > /proc/mi_modules/mi_ao/mi_ao0
    echo "set_ao_volume 1 -30dB" > /proc/mi_modules/mi_ao/mi_ao0

}

set_snd_level &
```

2. Remove [these below lines](https://github.com/shauninman/MinUI/blob/8e57805e9d29046427ee88762d9099fe7daf787a/skeleton/SYSTEM/miyoomini/paks/MinUI.pak/launch.sh#L72-L80) in `MinUI.pak/launch.sh`. As far as I know, this is the fix for the "pop noise" issue, which I think that it is relevant to the "Audio Fix" setting mentioned here. Removing this patch causes the regression bug "pop noise", but we have the sound for Drastic.
```bash
if $IS_PLUS; then
	/customer/app/audioserver -60 & # &> $SDCARD_PATH/audioserver.txt &
	export LD_PRELOAD=/customer/lib/libpadsp.so
else
	if [ -f /customer/lib/libpadsp.so ]; then
	    LD_PRELOAD=as_preload.so audioserver.mod &
	    export LD_PRELOAD=libpadsp.so
	fi
fi
```

**Comment by jmapagchema** [comment]
Thanks mate!
It works perfectly with 1.7 ;)

**Comment by dleicht** [comment]
@steward-fu you might want to consider mentioning this fix in the miyoo mini (plus) section of your README 🙏

**Comment by DesiQuintans** [comment]
Cheers, this works for me with:

- Miyoo Mini Plus
- [MinUI-20240128b-0](https://github.com/shauninman/MinUI/releases/tag/v20240128b-0)
- [v1.8 of this repo's releases](https://github.com/steward-fu/nds/releases/tag/v1.8)

I inserted the first part into "Emus\miyoomini\NDS.pak\launch.sh":

```bash
if [ "$CUST_CPUCLOCK" == "1" ]; then
    ./cpuclock 1500
fi

# INSERT THE FIX HERE

./drastic "$1"
sync
```

For the second part of the fix, I found the code in "K:\.system\miyoomini\paks\MinUI.pak\launch.sh" (after line 70) and commented it out (put # in front of every line).
