### ISSUE TITLE
Screenshot Feature review

### ISSUE THREAD

**Issue by schmurtzm** [steward-fu/nds#41]
- The next screenshot feature is making screenshots upside down.
- The file name could be prefixed with "Drastic_" or "NDS_"
- On Onion the screenshot shortcut is available from everywhere (including Drastic) with "menu + power" shortcut. So it's duplicated feature but not a problem however.

**Comment by steward-fu** [comment]
If the screenshot for resolution 752x560 works on Onion system, I will disable this feature for miyoo mini (plus) build.

**Comment by steward-fu** [comment]
I think that the hotkey of "MENU + X" can be used in MIC support for miyoo mini (plus).

**Comment by steward-fu** [comment]
disable the function of screenshot in drastic for miyoo mini (plus), commit: https://github.com/steward-fu/nds/commit/86eaa9cc1d1324d068a6b551854041b62a9ba7be
