### ISSUE TITLE
Drag on touch possible? 

### ISSUE THREAD

**Issue by V33p4s** [steward-fu/nds#42]
I startet worms open warfare and in the tutorial it requires you to drag the map on the touchscreen. I wasn't able to do it.. Is this integrated and I just missed it? I tried keeping the a button pressed and then move the cursor whole in stylus mode on bottom screen but It didn't work.

I'm on drastic 1.7 and onion 4.2.3

**Comment by steward-fu** [comment]
Interesting feature, I like it :)

I will try this game ("Worms: Open Warfare") and then think how to improve it, thanks for your suggestion :)

**Comment by steward-fu** [comment]
I tried drag (pressed A and then move the DPAD) rectangle on map as the following image and it worked:
![0371 - Worms - Open Warfare (U)(Trashman)_000](https://github.com/steward-fu/nds/assets/10125704/74987955-6c9c-400c-a8a6-fb6ff76e8555)

Or could you please describe the issue more detailed, thanks ?
