### ISSUE TITLE
Display mode 0 and display mode 1 screens are inverted

### ISSUE THREAD

**Issue by jdbrayshaw** [steward-fu/nds#47]
Display mode 0 and display mode 1 show in their preview that the secondary display (blue rectangle) should be the smaller one. However, when alternating between this mode and the normal full-screen primary display (full red rectangle), the screens swap from where they should be (i.e. if the primary display was the full-screen display, then it becomes the small corner display when switching to one of these modes). This is my favorite pair of modes to use otherwise for pokemon due to the transparency. Thank you!

**Comment by steward-fu** [comment]
test build:
https://drive.google.com/file/d/1o7-P3uFCOWp7CPuI521-R1dxRg8LV7E1/view?usp=sharing

commit: https://github.com/steward-fu/nds/commit/0c737bda63dff18f0f8beb2bd873f408f5317001
