### ISSUE TITLE
Auto-Save/Load breaking some games

### ISSUE THREAD

**Issue by shakerxx** [steward-fu/nds#48]
The auto-state feature (which i really love) is sadly breaking some games on the miyoo mini plus. An example constitutes Animal Crossing WW which freezes at game start if auto-state is enabled in settings.json. If there is no game state (i.e. new game) it will start, however, it will freeze after the introductory taxi scene.

**Comment by steward-fu** [comment]
May I know which version of drastic and OS you are testing ?

**Comment by shakerxx** [comment]
Sure:
Drastic v1.7
Onion OS v4.2.3

Mad respect for your work!

**Comment by steward-fu** [comment]
I can reproduce this issue and it is related to DraStic emulator itself.
So far, no any solution for such kind of problem.
The game of Pokémon White has this issue also.

I noted these games in this ticket:
https://github.com/steward-fu/nds/issues/8

**Comment by steward-fu** [comment]
Added into https://github.com/steward-fu/nds/issues/8
