### ISSUE TITLE
Is there a way to quickly check the savestate/ROM is working or not ?

### ISSUE THREAD

**Issue by steward-fu** [steward-fu/nds#54]
Reverse DraStic emulator to find out some useful functions for quick testing.

**Comment by Sichroteph** [comment]
First, I am not sure these freeze can be 100% prevented. 
If you had a way (file size, or maybe a bit presence in the file) it could come in handly for 
1) unfreezing drastic or prevent it to load it
2) maybe load a state backup instead (for the auto load on boot feature)

**Comment by steward-fu** [comment]
Could you please attach both the corrupted savestate and the normal savestate files on this issue.
Thanks

**Comment by Sichroteph** [comment]
I don't have any but we will ask for them when an user is experiencing this.

**Comment by steward-fu** [comment]
For the first stage, I think I can remove the sigterm() for Onion system and then restart the game if the rendering function in SDL2 library doesn't be called by drastic emulator for a period of time (ex: 3 seconds).

**Comment by Sichroteph** [comment]
That seems a great idea 👍
As soon as the binary is ready we will publish an hotfix. Thank you.

**Comment by Sichroteph** [comment]
Initially, the 3-second timer isn't essential; I'm optimistic that deactivating the handler should suffice. However, there's a risk of introducing new bugs that could result in the player losing progress. For instance, if the screen is turned off right after launching Drastic, the process is suspended, but the clock might not be.

**Comment by steward-fu** [comment]
@Sichroteph 
Here is the test build: https://drive.google.com/file/d/1ENpXHI_e0-YHH5oAFB8asEyiOXJesrEt/view?usp=sharing
In this test build, I only disabled sigterm for test. For the corrupted savestate, I think we need know the file format of savesate and then we can check why the are corrupted.

**Comment by schmurtzm** [comment]
Thank you ! [Here one corrupted savestate](https://cdn.discordapp.com/attachments/1159221156520398928/1196573227858792468/0079_Bomberman_EUM5_10.7z) which trigger a white screen.  And [here another one](https://dl.dropbox.com/scl/fi/i8a01ijf7d1bczccyg363/0079-Bomberman-EU-M5-_10.7z?rlkey=o7mazb1brzdla72j2etcizwe6&dl=0) on the same game which is working.

**Comment by Sichroteph** [comment]
@steward-fu 
Thank you for providing the test build. Nevertheless, it still responds to sigterms, and it required two attempts to corrupt a savestate using the "kill -TERM {pid}" command on telnet. 
Here is the corrupted state it made.
https://drive.google.com/file/d/1RVMtuZVqKPjRJ8aJ396UEx-kf8BZh5yX/view?usp=sharing

Launching this corrupted state now redirects to mainUI instead of remaining stuck on a white screen.

**Comment by Sichroteph** [comment]
@steward-fu 
We conducted tests internally and have concluded that preventing the arrival of the sigterm to the drastic appears to be impossible. Nevertheless, could you explore the possibility of preventing a state from being created when the sigterm arrives on your end? In such a scenario, drastic would exit without saving anything. However, please note that exiting through the menu + button shortcut would still result in the creation of a save state. Do you believe this is a feasible solution?

**Comment by steward-fu** [comment]
I can use a new flag for such scenario.
Set this flag as false if the sigterm() is triggered.
Set this falg as true if the hotkey is pressed.

And finally, when SDL2 library is exiting, we can decide whether the svaestate is needed or not.

**Comment by steward-fu** [comment]
I created a new branch for this issue (corrupted_savestate) and added the a new flag to handle sigterm: https://github.com/steward-fu/nds/commit/3808bf4d77e33b5cb508f998cf0d0f1af4abe425

When SDL2 gets a termination signal, it calls set_sigterm_flag() in alsa library to set this flag. The savesate xxx_10.dss won't be created if this flag is set as non-zero when drastic emulator is exiting.

**Comment by Sichroteph** [comment]
Thank you! We've made some adjustments to our keymon as well, such as avoiding the sending of multiple exit commands and extending the waiting time to more than 8 seconds for drastic to exit. 
We hope these changes will address the auto sleep issue your users have been experiencing.

**Comment by steward-fu** [comment]
If so, do you think we still need disable sigterm() function and stop writing savestate file (xxx_10.dss) if the sigterm is triggered.

**Comment by steward-fu** [comment]
If this issue doesn't exist anymore, please help close this case, thanks in advance.

**Comment by Sichroteph** [comment]
Sure you can close this case (I don't think I have the rights to do so, since you created it) 
Thanks !
