### ISSUE TITLE
NDS Layouts

### ISSUE THREAD

**Issue by judecambridge** [steward-fu/nds#56]
Didn't know how else to message; if you're still working on the emulator is there any chance you could do a layout like layout 8, but centralised like layout 10? 

If thats possible that would be amazing as it seems in my mind to be best of both? 😅

**Comment by steward-fu** [comment]
So far, since all of background images are created by different user, therefore, it is hard to add a new layout. For this request, I think I can add "customized layout" for user to adjust the window by demand.

**Comment by steward-fu** [comment]
New layout added (layout 8 with center): https://github.com/steward-fu/nds/commit/87f3fecd25cd14bff9e0c5b944bfb596a7dd35b9
After the background images are added into this repo, I will provide the test build for testing.

**Comment by steward-fu** [comment]
test build: https://drive.google.com/file/d/1iHrA1HBw1kkSJEy0qFo8RrWcjuqNrznH/view?usp=sharing

**Comment by judecambridge** [comment]
Thank you so much for working on it, it clearly took a lot of time! I
encountered a couple of issues whilst testing it so thought I should pass
them on to you :)

Sometimes when inside a game the home button wouldn't work, nor would the
power button on occasion (only allowing for a long press of the power
button to force stop the device).
Also the background images for themes 6 & 7 were missing.
And on low power drastic had some issues, mostly with the stylus. I can
provide videos of these if need be!

Thanks again,
Jude Cambridge :)

**Comment by steward-fu** [comment]
Let us discuss these issues in https://github.com/steward-fu/nds/issues/66
I closed this ticket.
Thanks
