### ISSUE TITLE
Exiting Drastic 1.8 (hotkey + L1) does not fix the issue in Dragon Quest IX asking for the system to close after choosing not to continue after saving

### ISSUE THREAD

**Issue by dothackjhe** [steward-fu/nds#58]
In addition, even forcing the Miyoo Mini Plus to force close does not address this. As soon as the game is re-run, it opens on the same part where the system is asking to be closed.

**Comment by steward-fu** [comment]
I cannot understand this issue well, is it possible to explain the reproducible steps to me ?
