### ISSUE TITLE
Fast Forward Speed on Miyoo Mini Plus not changing

### ISSUE THREAD

**Issue by inurbackline** [steward-fu/nds#59]
In the Custom Menu there's the option to set the speed from 1 upwards, with a 6 in Brackets.
The Setting saves the first number but the 6 Stays in Brackets, and the actual Fast forward speed never changes.

**Comment by inurbackline** [comment]
Actually, higher setting seems to make it faster, but the slowest fast forward is still way too fast, so some more customizability would be amazing.

**Comment by Benman2785** [comment]
FF should be:
1 = 100%
2 = 125%
3 = 150%
4 = 175%
5 = 200%
6 = 300%
