### ISSUE TITLE
(Feature Request) Retroachievements Miyoo Support

### ISSUE THREAD

**Issue by jujemido** [steward-fu/nds#60]
Helloo! 

Having Retroachievements would be ideal!

**Comment by steward-fu** [comment]
Did you mean the RA core ? ex: drastic.so ?

**Comment by jujemido** [comment]
Yup!

**Comment by oherau** [comment]
Other emulators already have that feature such as melonDS and DeSmuME.
I can't wait to see that feature implemented !

**Comment by oherau** [comment]
melonDS and DeSmuME already have this feature implemented but they are not available for Miyoo for now

**Comment by steward-fu** [comment]
This will be a big efforts to provide such RA core because we don't have the source code of DraStic emulator. So, please ask DraStic development team for this feature, thanks.

**Comment by oherau** [comment]
> This will be a big efforts to provide such RA core because we don't have the source code of DraStic emulator. So, please ask DraStic development team for this feature, thanks.

100% agree. The only effort Onion team should provide is to adapt the build for the target device.
RA support is a complete feature to implement on the emultator side.
