### ISSUE TITLE
Trimui Smart: power off without shutting down drastic corrupts saves. V1.8

### ISSUE THREAD

**Issue by DNPLukeBu** [steward-fu/nds#63]
If I save or save state in multiple games, and then shut off power (even after waiting a while), I can't resume play by loading.  I need to repair the drive with windows to fix it, and then saves made afterwards work until I shut it off again.  Saving, and then exiting DraStic through the menu before shutting off each time works properly, and the saves are then functional.

**Comment by DNPLukeBu** [comment]
I am using MinUI if that is relevant.

**Comment by steward-fu** [comment]
Only stock system is supported. Please use stock system for this emulator, thanks.

**Comment by DNPLukeBu** [comment]
Thanks!  I'm just going to close it all down manually since I like both programs.  Thank you for your response!
