### ISSUE TITLE
(Feature Request) MinUI support on Miyoo

### ISSUE THREAD

**Issue by offalynne** [steward-fu/nds#64]
Hello, thank you so much for all your great work here! The launch script works great for MinUI on TrimUI Smart but sound is not working on Miyoo thru MinUI, was hoping you might be able to work out a fix. Thanks again ! :-)

**Comment by steward-fu** [comment]
https://github.com/steward-fu/nds/issues/57

**Comment by offalynne** [comment]
Thank you, will try this and confirm

**Comment by offalynne** [comment]
Works for me as well, thank you kindly
