### ISSUE TITLE
Feature Request: Centred equivalent for layout 8 (480x360 and 160x120)

### ISSUE THREAD

**Issue by michal-korniak-kornit** [steward-fu/nds#66]
Hi
I've noticed that Layout 10 is essentially Layout 9, but centered horizontally. However, there appears to be no centered equivalent for Layout 8, which would be more suitable for my needs. Could you add one? Alternatively, is there a way for me to adjust it myself?

**Comment by steward-fu** [comment]
New layout added (layout 8 with center): https://github.com/steward-fu/nds/commit/87f3fecd25cd14bff9e0c5b944bfb596a7dd35b9
After the background images are added into this repo, I will provide the test build for testing.

So far, user cannot adjust the layout manually.

**Comment by steward-fu** [comment]
test build: https://drive.google.com/file/d/1iHrA1HBw1kkSJEy0qFo8RrWcjuqNrznH/view?usp=sharing

**Comment by judecambridge** [comment]
Thank you so much for working on it, it clearly took a lot of time! I encountered a couple of issues whilst testing it so thought I should pass them on to you :)

Sometimes when inside a game the home button wouldn't work, nor would the power button on occasion (only allowing for a long press of the power button to force stop the device).
Also the background images for themes 6 & 7 were missing.
And on low power drastic had some issues, mostly with the stylus. I can provide videos of these if need be!

**Comment by steward-fu** [comment]
For HOME button, please give the reproducible steps to me.
For the missing images, they will be added into this repo after the developer provides to me.
For low power, please give the reproducible steps to me.

Thanks

**Comment by steward-fu** [comment]
here is the test build (added the missing images): https://drive.google.com/file/d/1ZVcP_WRHiUW7KJeg2LIKljY9sICEZ_tA/view?usp=sharing

**Comment by judecambridge** [comment]
> For HOME button, please give the reproducible steps to me. For the missing images, they will be added into this repo after the developer provides to me. For low power, please give the reproducible steps to me.
> 
> Thanks

I should say, to install it i replaced the files in Emu/NDS (Except savestates), and it now shows as drastic. Basically for the home button i used 'Menu + Start' to open the drastic menu, and when attempting to exit to the main menu from there it didn't work (same thing happened with the power button sometimes). Then when i left the drastic menu to return to the game, the menu button no longer worked in the game (and on occasion the power button too).

For low power i simply had it in a game whilst the red 'low power' icon flashed at the top, and it made the stylus glitch and hover over the large screen too. For some reason during this the theme of my onion OS reset to the default too?

Hope that helps :)

**Comment by judecambridge** [comment]
[https://drive.google.com/drive/folders/1Syju9Ddt9lD3EVZ1hYZqmNig6vxldbOE?usp=drive_link](url)

**Comment by steward-fu** [comment]
Thanks for your information. Might I know which version of Onion you are using ?

**Comment by judecambridge** [comment]
> Thanks for your information. Might I know which version of Onion you are using ?

V4.3.0

**Comment by michal-korniak-kornit** [comment]
> test build: https://drive.google.com/file/d/1iHrA1HBw1kkSJEy0qFo8RrWcjuqNrznH/view?usp=sharing

Works correctly. thank you!

**Comment by steward-fu** [comment]
@judecambridge 
For pen's blink issue, it is a bug and here is the test build for this issue: https://drive.google.com/file/d/144I5lKJx5wkDDXkctFNIxzfbCFFitKr1/view?usp=sharing

For power button issue, basically, this emulator doesn't support this feature. The feature should be handled by system, not emulator itself. So, I will list this issue as known issue.
