### ISSUE TITLE
EUR multilanguage roms only in english

### ISSUE THREAD

**Issue by Benman2785** [steward-fu/nds#67]
Hi, how to set NDS firmware to german?

also i can help translating the emu into german :)

**Comment by steward-fu** [comment]
The firmware is provided from DraStic emulator, not from this repo.
For translation into German, here is the way you can do: https://github.com/steward-fu/nds?tab=readme-ov-file#q--a
"How to add a new language"

**Comment by Benman2785** [comment]
ok - found how to play in german.
but i will also proivde a german translation :)

**Comment by steward-fu** [comment]
Thanks for your information. You can use PR or provide the translation file to me and then I can add into this repo.

**Comment by Benman2785** [comment]
here is my german translation

[german_deu.txt](https://github.com/steward-fu/nds/files/15110348/german_deu.txt)

**Comment by steward-fu** [comment]
Thanks for your file. Here is the test build: https://drive.google.com/file/d/17Qs5n8YODKvdGfFgUfT-UGlRwkj0O5hm/view?usp=sharing
Please let me know whether it works as expected or not.
Thanks

**Comment by Benman2785** [comment]
i simply added it into ./resources/lang/ and tested it:

here is a better version:
[german_deu.txt](https://github.com/steward-fu/nds/files/15111572/german_deu.txt)

**Comment by steward-fu** [comment]
Added into this repo: https://github.com/steward-fu/nds/commit/baf343da4dd2d6e0f7611723c218deee2d7b5107
Thanks
