### ISSUE TITLE
(Feature Request) Support for TrimUI Smart Pro

### ISSUE THREAD

**Issue by odyssey46** [steward-fu/nds#68]
Hello, I wonder if there would be any interest in adding support for the TrimUI Smart Pro? This device seems to be growing in popularity due to recent price drops and increased developer interest elsewhere in the community. With its 16:9 aspect ratio, this device would really benefit from some custom layouts - for example, having the primary screen larger and the secondary screen smaller and on the side.

This device uses the Allwinner A133P. I'm not sure if any of the existing work from the TrimUI Smart (using Allwinner S3) could be leveraged.

**Comment by steward-fu** [comment]
The Trimui Smart Pro is based on aarch64 architecture but this emulator is designed for armhf (arm32). Unless the system is compatible with armhf, which means the ELF binary in armhf format can run on Trimui Smart Pro, or it is impossible to port this emulator into Trimui Smart Pro. Chroot may be a way to run this emulator on aarch64 system. But what I want to say is no any planning so far for this port. Thanks
