### ISSUE TITLE
Bug regarding full terminators in Action Replay codes

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [steward-fu/nds#69]
The following cheat code for Yu-Gi-Oh! 5D's World Championship 2011: Over the Nexus (US version, BYYE) does not work on my Miyoo Mini Plus. I have tested all other codes, only this one does not work; this issue is also prevalent on some of the first NDS flashcarts that supported Action Replay codes, although only on ones that didn't have firmware updates. The issue is that the first full terminator is falsely interpreted as the end of the code, and if there's more to the code after that (and there can be, particularly with codes that are 'Off' by default, with the next lines enabling the code via button press, like the below code), then the rest of the code is ignored.

There is obviously a workaround that can be employed to make codes affected by this 'bug' work, which is simply to add the correct amount of D0 (single terminator) codes to complement the number of conditional codes, but this is far from ideal.
Here is the cheat that doesn't work:

```
94000130 FEFF0100
52172578 EA000038
02172578 0A000038
D2000000 00000000
94000130 FEFF0000
52172578 0A000038
02172578 EA000038
D2000000 00000000
```

Edit: While testing the D0 codetype replacement method I quoted above, I found another bug: the cheat list doesn't load when it finds a D0 codetype in a code. The following code causes the code list not to load, as if cheats were altogether disabled:

```
52172578 EA000038
02172578 0A000038
D0000000 00000000
94000130 FEFF0000
52172578 0A000038
02172578 EA000038
D2000000 00000000
```

So there are actually 2 bugs regarding Action Replay codes.

**Comment by M1CR0H4CK3R** [comment]
Okay, I deleted the above code, and the cheat list still won't load for this game... The cheat list loads fine for the other games I have, I checked that already. Now to deduce which cheat is causing the issue...

**Comment by M1CR0H4CK3R** [comment]
Okay, apparently my CRC32 doesn't match now, which is extremely odd...

**Comment by M1CR0H4CK3R** [comment]
Okay, I rebuilt my usrcheat.dat file and deleted all but 3 games, and now none of my games allow cheats...
[usrcheat.zip](https://github.com/steward-fu/nds/files/15052995/usrcheat.zip)
There is my usrcheat.dat file that I am trying to use. My CRC32s and game IDs all match perfectly what is in that file, I triple-checked. Is there a cache for which cheats are enabled or something? If so, where is it saved? I really want to clear it ASAP.

**Comment by M1CR0H4CK3R** [comment]
I have just tried using Package Manager to remove, then reinstall, the DraStic emulator, then replaced the usrcheat.dat file included by default with my edited copy, and the issue still persists, which means that it is something inside the 'cachefile' file in the SD card root that is somehow being kept from my initial copy of usrcheat.dat, and I am unsure if it is safe to remove that file, as it is 128MB in size, so I am backing it up on my PC before attempting to delete it and rebooting. If this solves nothing, then I have absolutely zero clue as to how to fix this issue.

**Comment by M1CR0H4CK3R** [comment]
Okay, I figured out the exact issues that I was having. Regarding the cheat code not working:

Turns out it is a bug with how the Linux binary (that we don't have the source code for) handles input polling in regards to the emulator's clock speed. Higher clock speeds (at least 2100Hz) are going to be required to get real console accurate input polling frequency, and due to the lower clock speed needed to get this emulator to even run well on MM+ (1500MHz), approximately 1 in 4 input polls don't happen. When using a walk through walls code (like the one above), the walls pushing back the player combined with the missed polling frames makes the code appear to not work. The workaround (and the only valid one here) is to have a code that enables walking through walls, and another to disable it (which requires turning off the enable code first). Only one of these codes can be activated at a time, obviously.


Regarding the other issue regarding all my other games stopping working:

It turns out that right before the issue started, I removed about 16 codes for the affected game in addition to deleting codes for over 600 games, which shrunk the file size dramatically (by 42MB, actually; I initially was using DeadSkullzJr's cheat database, which is about 53.1MB. By comparison, the default usrcheat.dat file included with the emulator is 15.3MB). Turns out that for some odd reason, the main binary has a minimum offset for specific games hardcoded for the usrcheat.dat file, and once the file size becomes less than an offset, games at file offsets that are less than the nearest previous hardcoded game's hardcoded offset are not detected, at all. I have zero clue why this was implemented at all, probably some quirk with memory in certain Android versions that had to be worked around. Either way, this is an extremely egrigious bug, and if it weren't for my due diligence, it would've never been discovered how to fix it.

**Comment by steward-fu** [comment]
Thanks for your information. Accroding to your description, it seems this issue is reated to emulator performance. Is my understanding correct ? Since the cheat code is handled by DraStic emulator, not SDL2 library, therefore, it is hard to fix if it is a bug.

**Comment by M1CR0H4CK3R** [comment]
> Thanks for your information. Accroding to your description, it seems this issue is reated to emulator performance. Is my understanding correct ? Since the cheat code is handled by DraStic emulator, not SDL2 library, therefore, it is hard to fix if it is a bug.

@steward-fu 

Yes, the issue is that emulator performance causes missed input polls done by the Action Replay codehandler on the 0x04000130 address, which causes ineffective button press based walk through walls codes on some games, like the one in the issue itself.

As for the second issue I came across, it has to do with hardcoding minimum addresses of parts of the usrcheat.dat file, which means that you need a minimum amount of games each with a minimum amount of cheats in the list in order for all cheats to be detected; DeadSkullzJr's cheat database works fine unedited in the emulator, but removing a certain number of games from the database can cause some games not to be detected by the emulator. You can safely include DeadSkullzJr's database in your source here if you want; all of my games properly detect cheats when using that database, including the game that the cheat in the OP is from.

As mentioned above, certain button held walk through walls cheats won't work in the database, so I will upload an edited version of DSJ's database with the cheat in the OP 'fixed' in this post for your addition to the source code here. I also added 3 cheat codes that I ported (tested working) for the game in the OP as well, as well as added the 'Instant Win' cheat code found in some places online.
[usrcheat.zip](https://github.com/steward-fu/nds/files/15119674/usrcheat.zip)

**Comment by steward-fu** [comment]
Thanks for your detailed description for cheat issue.
Since the cheat file (usrcheat.dat) included in this emulator should be updated by user to fit their needs, so, this is why I keep the original file provided from DraStic emulator (only 13MB size). So, any bug fix for cheat won't be updated into this repo. Sorry for this inconvenience.
