### ISSUE TITLE
Stylus/Pen stuck on small screen 8

### ISSUE THREAD

**Issue by Benman2785** [steward-fu/nds#70]
Hi,

Miyoo Mini Plus

when i use Screen 8 (480x360 + 160x120) the Stylus/Pen is ALWAYS on the small screen - even when i swap screens so that touchscreen is 480x360

touch input works - but its hard to see what i am doing :)
funny is that after switching from screen 0 to screen 8 it works - until i restart DraStic

**Comment by Benman2785** [comment]
also we need do disable acceleration of stylus - so only use raw input

**Comment by steward-fu** [comment]
Have you tried 'MENU + UP' and 'MENU + DOWN' to change the touch position ?

**Comment by Benman2785** [comment]
so it was a RTFM for me - it works :)
