### ISSUE TITLE
[Feature Request] RG35XX plus port

### ISSUE THREAD

**Issue by dvrkoo** [steward-fu/nds#71]
Hello, thanks for the incredible work, could the rg35xx plus get a port of this drastic version?
It has a H700 SoC 4-core 64-bit CortexTM-A53 processor, and the G31 GPU

**Comment by dvrkoo** [comment]
actually building for the miyoo mini works on the RG35XX plus but no key is working, changing drastic/config/drastic.cfg to the one used in the device version of drastic make the keys work but custom menu is not working (select + start)

**Comment by namnq-sipher** [comment]
+1. I ended up using the Miyoo version on my RG35XX Plus but there're issues unfortunately.

**Comment by namquang93** [comment]
+1. I ended up using the Miyoo version on my RG35XX Plus but there're issues unfortunately.

**Comment by steward-fu** [comment]
Due to personal reason, Anbernic will not be in the support list.
