### ISSUE TITLE
Save states not working on Retroarch

### ISSUE THREAD

**Issue by Goldensun7** [steward-fu/nds#72]
Hello community! 

First, thank you for reading me. I have a question about saving states in RetroArch. Every time I hit "save state", it saves in a random one. When I played on the emulator on PC, at least in the Mgba emulator, you have 8 states to save, you choose where you want to save it, and the same for loading it. You go to "load state" and choose which one you want to load. But in this emulator console, it's not like that. It saves in a random slot, and if I save another, it's the same. So, I can't load the one I want; it's random and I don't understand it. It also happens that, for example, I choose to save it in slot number 1, but when I hit save, it puts it in 2... and so on
I am using GPSP core but I think its the same for Mgba or any other...

Can anyone help me please!

cheers!

**Comment by steward-fu** [comment]
This repo is only for DraStic emulator, not RetroArch.
Please file your issue to: https://github.com/OnionUI/Onion
