### ISSUE TITLE
No sound in trimui smart OFW 1.0.0 RC5

### ISSUE THREAD

**Issue by wilverportella** [steward-fu/nds#74]
The emulator has no sound in the new version of the original trimui smart firmware, 1.0.0rc5 , everything else seems to be working normally. It appears that the trimui developers have modified the sound system. Here is the changelog and firmware link:

[https://drive.google.com/file/d/1b4HGtSf6lqnHZluxE-pwlm8EaTJZEuYx/view?usp=sharing](url)
[https://drive.google.com/file/d/1QrWZ_mxigQmnNHdxY7m8BL_zinA8Tu9-/view?usp=drive_link](url)

firmware - v1.0.0rc5. 20240503  (diff from 0.117)
===========================
1. **Update the Bluetooth logic as SmartPro, and all applications automatically use Bluetooth and USB audio.**
2. Update the WiFi logic as SmartPro, allowing for password modification and multiple records.
3. Add X menu launch selection support.
4. Fixed the netplay between smart and Smartpro.
5. Fix the issue of hotspot netplay where hotspots cannot be used as hosts.
6. Fix issue when using 'png' as extlist in config.json and ext case sensitive.
7. Add low-battery LED support, with red double flashing.
8. Add LED indicating that the machine auto-turn-off screen (Telling it is not really shutdown.).
9. Upgrade the RetroArch (ra32.trimui/ra32.trimui_sdl) to version 1.18.0.
10. Developer related: Add standard battery drivers class and fix occasional crashes when RetroArch reads batteries.
11. Change MainUI icons (improve contrast).
12. Change expression (as SmartPro) in the device info page.
13. Fix game list text length display issue.
14. SD card hotplug support.
15. Fix issue: SD card becoming read-only when encountering errors.
16. Remove CPU settings in MainUI. Fine tune the CPU frequency logic for each Emu launch.sh. Check 'Emus/_sample_cpufreq_scripts' to find cpufreq.sh to replace.
17. Add multiple languages (Chinese/English/Portuguese/Spanish/German/Italian/French/Japanese/Korean/Russian).
18. Bug fix: do turn off wifi power when WiFi and bluetooth switches are both off.
19. Default grid display.
20. Add fake RTC. The system time will save and recover at the next boot. (except 1970~2023). Please use WiFi NTP time synchronization first.
21. Fix MainUI graphic tearing.
22. Fixed issue 'Wi-Fi will be turned off when returning from a game'.
23. Fixed issue 'No Chinese item in language setting'.

**Comment by steward-fu** [comment]
Here is the test build: https://drive.google.com/file/d/1U4oh3SpRgjgtd0l0EqiXE_zanjp5xeqN/view?usp=sharing

**Comment by wilverportella** [comment]
Sound working again! Thanks! BT still not working yet thought. The devs said they changed the sound system from  OSS to ALSA. Does it helps fixing it?

**Comment by steward-fu** [comment]
If they can provide some reference code (how to play audio through ALSA bluetooth), it can help me a lot.
Thanks

**Comment by steward-fu** [comment]
This device was dropped in the supported list, thanks.
