### ISSUE TITLE
Touch pen only covers a portion of the screen if 'High Resolution 3D' turned on

### ISSUE THREAD

**Issue by willemprins93** [steward-fu/nds#85]
(Running muOS v2410.1 — Anbernic RG35XXH)

When 'High Resolution 3D' is turned on, the simulated touch pen only covers the top left quarter of the screen, making it unusable. Once the resolution setting is turned off it works as intended again.

**Comment by steward-fu** [comment]
Sorry, all of Anbernic devices are not in the support list.
