### ISSUE TITLE
lack of screenshot function on retro handhelds

### ISSUE THREAD

**Issue by skyhighcaterpie** [steward-fu/nds#86]
I try to take a game screenshot (hotkey: menu+L1) on my miyoo-mini-plus(OnionOS) and RG35XX-plus(Knulli), but both not working, please add screenshot hotkey.

**Comment by steward-fu** [comment]
For miyoo-mini-plus(OnionOS), this function should be provided from OnionOS. Might I know which version you are using on Miyoo Mini Plus ? For RG35XX-plus(Knulli), all of Anbernic devices are not in the support list anymore.

**Comment by skyhighcaterpie** [comment]
Oh thanks, you are right. I can screenshot (menu+power) on Onion v4.3.1-1. Just can't do screenshot on RG35XX-plus(Knulli) (melonDS has screenshot function on RG35XX+, but its display is not good as DraStic).
